project:
  type: website
  output-dir: .. # output to the parent directory

website:
  title: "Patricio Pantaleo's Blog"
  description: "Digital Humanities & Academic Publishing"
  site-url: "https://patricio.pantaleo.ar/blog"
  favicon: logo.png
  navbar:
    logo: logo.png
    logo-alt: "Patricio Pantaleo"
    logo-href: "https://patricio.pantaleo.ar/"
    toggle-position: right
    title: false
    background: "#f3f3f4eb"
    foreground: "#333333"
    right:
      - text: "About"
        href: https://patricio.pantaleo.ar
      - text: "Blog"
        href: https://patricio.pantaleo.ar/blog
      - text: "Resources"
        href: https://patricio.pantaleo.ar/recursos
      - text: "Contact"
        href: https://patricio.pantaleo.ar/#contact
      - icon: rss
        href: index.xml

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    dark: 
      - darkly
      - custom.scss
    css: styles.css
    toc: true
    toc-location: right
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    fontsize: 1.1em
    linestretch: 1.7
    include-in-header: "header.html"
    include-after-body: footer.html
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/'

execute:
  freeze: auto